/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/App.js",
    "./src/componentes/GameListPage.jsx",
    "./src/componentes/ReviewsPage.jsx",
    "./src/componentes/SearchPage.jsx",
    "./src/componentes/GameDetails.jsx",
    "./src/componentes/languageDropdown.js",
    "./src/componentes/background2.js",
    "./src/componentes/Layout.jsx",
    "./src/componentes/Reports.jsx",
    "./src/componentes/FiltersPage.jsx",
    "./src/componentes/ReviewCard.jsx",
    "./src/componentes/InsightPage.jsx",
    "./src/componentes/SearchBar.jsx",
    "./src/componentes/GameCard.jsx",
    "./src/componentes/LoginForm.jsx",
    "./src/componentes/Registo.jsx",
    "./src/componentes/ComparePage.jsx",
    "./src/componentes/SignupSteps/StepTwo.jsx",
    "./src/componentes/SignupSteps/StepThree.jsx",
    "./src/componentes/GlassToast.jsx",
    "./src/componentes/ComparisonCard.jsx",
    "./src/componentes/ComparisonButton.jsx",
    "./src/componentes/GameComparison.jsx",
    "./src/componentes/CompareInfo.jsx",
    "./src/componentes/MetacriticScore.jsx",
    "./src/componentes/AIComparisonResult.jsx",
    "./src/componentes/AICompareButton.jsx",
    "./src/componentes/Library.jsx",
    "./src/componentes/Library/CreateFolderOverlay.jsx",
    "./src/componentes/Library/ButtonCreateFolder.jsx",
    "./src/componentes/BotaoTopo.jsx",
    "./src/componentes/Filters/TypeReview.jsx",
    "./src/componentes/Loading.jsx",
    "./src/componentes/LoadingAIComparison.jsx",
    "./src/componentes/LoadingCompare.jsx",
    "./src/componentes/LoadingCompareInfo.jsx",
    "./src/componentes/LoadingDetails.jsx",
    "./src/componentes/LoadingList.jsx",
    "./src/componentes/LoadingReviews.jsx",
    "./src/componentes/AddLibraryButton.jsx",
    "./src/componentes/AddToPastas.jsx",
    "./src/componentes/OverlayPastas.jsx",
    "./src/componentes/BackButton.jsx",
    "./src/componentes/FolderContentPage.jsx",
    "./src/componentes/Library/ConfirmDeleteFolder.jsx",
    "./src/componentes/Library/RenameFolderModal.jsx",
    "./src/componentes/Library/FolderEditControls.jsx",
    "./src/componentes/Reports/ReportsResults.jsx",
    "./src/componentes/Reports/ReportsSearchBar.jsx",
    "./src/componentes/Reports/ReportDetails.jsx",
    "./src/componentes/Reports/CartButton.jsx",
    "./src/componentes/Reports/Cart.jsx",
    "./src/componentes/navbar.jsx",
    "./src/componentes/Checkout.jsx",
    "./src/componentes/AddCardButton.jsx",
    "./src/componentes/OverlayAddCard.jsx",
  ],
  theme: {
    extend: {
      fontFamily: {
        sf: ["SF Pro Display", "sans-serif"],
        moonwalk: ["moonwalk", "sans-serif"],
      },
      keyframes: {
        bounceMouse: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(6px)" },
        },
      },
      animation: {
        bounceMouse: "bounceMouse 1.5s infinite",
      },
    },
  },
  plugins: [],
};
